GET http://https://ignite-api-thddfwkmye.now.sh/:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTY3Mzc5NzUsImV4cCI6MTUxNzM0Mjc3NSwic3ViIjoiNWE2Nzc3OTRiYjEzMjRkYzMwODhiMzhjIn0.jH2MtpI5GUJe8r_Ft_YQfv8fj7ktslRtT_EWAK0Mx8s

### Register
# POST https://ignite-api-myjuxrawek.now.sh/auth/register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "testadmin@ignite.com",
  "firstName": "Admin",
  "lastName": "User",
  "password": "password",
  "dateOfBirth": "1900/01/01",
  "address": "1 Admin Road",
  "postCode": "3000",
  "state": "VIC",
  "mobileNumber": "0404040404",
  "admin": true,
  "verified": true
}

### Sign In
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password123"
}
###

PATCH http://localhost:7000/auth/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTc3MzQyNzcsImV4cCI6MTUxODMzOTA3Nywic3ViIjoiNWE2Nzc3OTRiYjEzMjRkYzMwODhiMzhjIn0.6DEjkKNRJAeMs4FKQWj0SBDcvzvmyIFzPK-jRL_rfOI
Content-Type: application/json

{
  "oldPassword": "password123",
  "newPassword": "password456"
}
### Update User details

PATCH http://localhost:7000/auth/update-details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTc3MzQyNzcsImV4cCI6MTUxODMzOTA3Nywic3ViIjoiNWE2Nzc3OTRiYjEzMjRkYzMwODhiMzhjIn0.6DEjkKNRJAeMs4FKQWj0SBDcvzvmyIFzPK-jRL_rfOI
Content-Type: application/json

{
  "firstName": "Hello",
  "lastName": "World"
}