### Make a module
POST http://localhost:7000/module
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTY3Mzc5NzUsImV4cCI6MTUxNzM0Mjc3NSwic3ViIjoiNWE2Nzc3OTRiYjEzMjRkYzMwODhiMzhjIn0.jH2MtpI5GUJe8r_Ft_YQfv8fj7ktslRtT_EWAK0Mx8s
Content-Type: application/json

{
  "name":"The module 1",
  "content":"The best module in the world"
}
#### Make a question with module 

POST http://localhost:7000/question
Content-Type: application/json

{
  "content":"DEFINATELY JINOUR STUFF?",
  "module": "5a646ec6027e8c7064197201",
  "answers": [
    {"content": "A Racoon"},
    {"content": "A Horse"},
    {"content": "A Cat"},
    {"content": "A Dog"}
  ]
}
### Second question

POST http://localhost:7000/question
Content-Type: application/json

{
  "content":"is coder academy worth it?",
  "module": "5a62c1d8c87aa2eecae817d2",
  "answers": [
    {"content": "Yes"},
    {"content": "No"},
    {"content": "Definately"},
    {"content": "HORDOR"}
  ]
}
### Post right answer

POST http://localhost:7000/Answer
Content-Type: application/json

{
  "question": "5a66e50438bd1694290efe9d",
  "answer": "5a66e50438bd1694290efea0"
}
### Give a marking for the question if its correct

### The marking section
POST http://localhost:7000/marking
Content-Type: application/json

{
  "user": "5a6063319a86d5938b321e0b",
  "quiz": {"5a6063029a86d5938b321e06": "5a6063029a86d5938b321e08", "5a613549dd3a3ca7e2899fcd": "5a613549dd3a3ca7e2899fcf", "5a613556dd3a3ca7e2899fd2": "5a613556dd3a3ca7e2899fd4"}
}

### 

DELETE http://localhost:7000/module/5a6454a0879d7436afa3b055

