GET http://localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYy5jb20iLCJpYXQiOjE1MTYwMDMyNTYsImV4cCI6MTUxNjYwODA1Niwic3ViIjoiNWE1YzVmYjc2MTQ5NjU1ZDdiYTkwYjlhIn0.xpmydMb9Q6KaZW1QiUJ16ddkurcpl6YhIulrDzhIXaI

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "a@c.com",
  "firstName": "Nisal",
  "lastName": "Don",
  "password": "123456"
}

### Sign In
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "a@b.com",
  "password": "123456"
}
