GET http://localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAbC5jb20iLCJpYXQiOjE1MTYyMDAxMzQsImV4cCI6MTUxNjgwNDkzNCwic3ViIjoiNWE1ZjYwYjg0YzE0MWI2MzQ4YTY5NTc4In0.9yQAZNY86mpDQDK7o6-rylIMzSqp1DU3x66rIPtYHcQ

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "a@m.com",
  "firstName": "Nisal",
  "lastName": "Don",
  "password": "123456",
  "dateOfBirth": "1995/02/01",
  "address": "10 blagh Street",
  "postCode": "3802",
  "state": "VIC",
}

### Sign In
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "a@l.com",
  "password": "123456"
}
